name: Check latest CyberChef version

on:
  schedule:
    - cron: '21 */6 * * *'
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: "Set debug flag for manual workflow dispatch"
        required: false
        type: boolean

jobs:
  version_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          token: ${{ github.token }}
      - name: Get the latest version of CyberChef
        run: |
          curl -s https://api.github.com/repos/gchq/CyberChef/releases/latest | jq -r 'select(.prerelease == false) | .tag_name[1:]' > version
          export CYBERCHEF_VERSION=$(cat version)
          echo "CYBERCHEF_VERSION=$CYBERCHEF_VERSION" >> $GITHUB_ENV
      - name: Add & Commit
        id: commit_version_file
        uses: EndBug/add-and-commit@v9.1.1
        with:
          message: 'Version updated to: ${{ env.CYBERCHEF_VERSION }}'
      - name: Debug commit result
#        if: ${{ inputs.debug_enabled }}
        run: echo '${{ toJSON(steps.commit_version_file.outputs) }}'
