name: Check latest CyberChef version

on:
  schedule:
    - cron: "21 */6 * * *"
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: "Set debug flag for manual workflow dispatch"
        required: false
        type: boolean

jobs:
  get_latest_release:
    runs-on: ubuntu-latest
    outputs:
      release_tag_name: ${{ steps.release_info.outputs.tag_name }}
      release_version: ${{ steps.release_info.outputs.version }}
      release_description: ${{ steps.release_info.outputs.description }}
      release_file_name: ${{ steps.release_info.outputs.file_name }}
      release_download_url: ${{ steps.release_info.outputs.download_url }}

    steps:
      - name: Get release info for the latest version of CyberChef
        id: release_info
        uses: actions/github-script@v7
        with:
          script: |
            const {
              data: {
                tag_name: tag_name, body: description, assets: [{ name: file_name, browser_download_url: download_url }]
              },
            } = await github.rest.repos.getLatestRelease({ owner: "gchq", repo: "CyberChef" });
            const version = /^v(.+)$/.exec(tag_name)[1] ?? core.setFailed(`Failed to parse version from tag ${tag_name}`);
            const outputs = { tag_name, version, description, file_name, download_url };
            Object.entries(outputs).forEach(([k, v]) => core.setOutput(k, v));
            return outputs;

  compare_local:
    runs-on: ubuntu-latest
    outputs:
      update_available: ${{ steps.compare_version.outputs.version_changed }}
    needs:
      - get_latest_release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
      - name: Check if latest release is newer than local
        id: compare_version
        env:
          RELEASE_VERSION: ${{ needs.get_latest_release.outputs.release_version }}
        run: |
          jq 'if .version != env.RELEASE_VERSION then true else false end' package.json | \
            xargs -i -r echo "version_changed={}" >> $GITHUB_OUTPUT

  update_local:
    runs-on: ubuntu-latest
    if: fromJSON(needs.compare_local.outputs.update_available)
    outputs:
      local_commit_ref: ${{ steps.commit_version_file.outputs.version_tag }}
    needs:
      - get_latest_release
      - compare_local
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6.0.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
      - name: Update and tag local version
        id: commit_version_file
        run: |
          npm config set sign-git-commit true
          npm config set sign-git-tag true
          npm version ${{ needs.get_latest_release.outputs.release_version }} -m "Version updated to: %s"
          git push --follow-tags
          echo "version_tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

  trigger_build_workflow:
    if: fromJSON(needs.compare_local.outputs.update_available)
    needs:
      - get_latest_release
      - compare_local
      - update_local
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ needs.get_latest_release.outputs.release_version }}
      file_name: ${{ needs.get_latest_release.outputs.release_file_name }}
      download_url: ${{ needs.get_latest_release.outputs.release_download_url }}
      description: ${{ needs.get_latest_release.outputs.release_description }}
      local_commit_ref: ${{ needs.update_local.outputs.local_commit_ref }}

  debug_outputs:
    #    if: ${{ always() && inputs.debug_enabled }}
    if: always() # todo re-enable debug flag
    needs:
      - get_latest_release
      - compare_local
      - update_local
    runs-on: ubuntu-latest
    steps:
      - name: Debug commit result
        run: echo '${{ toJSON(needs) }}'
      - name: View context attributes
        uses: actions/github-script@v7
        with:
          script: console.log(context)
